### ISSUE TITLE
convert all the IC50 to micromolar on the plots

### ISSUE THREAD

**Issue by apratap** [Sage-Bionetworks/Synodos_NF2_SyDE_shinyApp#1]
If the conc is 10-7 molar we shud show 10 micromolar . (10 x 10-6 ) let me know if this makes sense ?

**Comment by apratap** [comment]
you can try it on internal release branch let me know I will see how it looks

**Comment by xindiguo** [comment]
The "IC50" column has been converted to micromolar in getData.R.
[https://github.com/Sage-Bionetworks/Synodos_NF2_SyDE_shinyApp/blob/master/getData.R#L25](url)
